# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_oficio', models.CharField(max_length=200)),
                ('remitente', models.CharField(choices=[('1', 'Departamentos de redes populares')], max_length=200)),
                ('fecha', models.DateField()),
                ('caso_planteado', models.CharField(max_length=200)),
                ('tipo_solicitud', models.CharField(choices=[('1', 'Personal'), ('2', 'Alto Riezgo'), ('3', 'Salud'), ('4', 'Institucional')], max_length=200)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
